version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk@2.161.1
      - cd Backend
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Building TypeScript sources..."
      - npm run build
      - echo "Bootstrapping CDK..."
      - cdk bootstrap --require-approval never

  build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stack...";
          cdk destroy CatholicCharitiesStack --force \
            --context githubOwner="$GITHUB_OWNER" \
            --context githubRepo="$GITHUB_REPO" \
            --context githubToken="$GITHUB_TOKEN" \
            --context projectName="$PROJECT_NAME" \
            --context urlFilesPath="$URL_FILES_PATH";
        else
          echo "Deploying CDK stack...";
          echo "URL files found in $URL_FILES_PATH:";
          ls -la "$URL_FILES_PATH"/*.txt || echo "No .txt files found in $URL_FILES_PATH";
          
          cdk deploy CatholicCharitiesStack --require-approval never \
            --context githubOwner="$GITHUB_OWNER" \
            --context githubRepo="$GITHUB_REPO" \
            --context githubToken="$GITHUB_TOKEN" \
            --context projectName="$PROJECT_NAME" \
            --context urlFilesPath="$URL_FILES_PATH" \
            --outputs-file outputs.json;
          
          echo "Deployment outputs:";
          cat outputs.json;
        fi

  post_build:
    commands:
      - echo "CDK $ACTION complete."
      - |
        if [ "$ACTION" = "deploy" ]; then
          echo "=== Deployment Summary ===";
          echo "✅ Q Business Application deployed";
          echo "✅ Lambda function deployed";
          echo "✅ API Gateway deployed";
          echo "✅ Amplify app configured";
          echo "✅ S3 data source bucket created";
          echo "";
          echo "Next steps:";
          echo "1. Wait for Q Business data source sync to complete";
          echo "2. Test the API endpoints";
          echo "3. Access your frontend via Amplify URL";
        fi

artifacts:
  files:
    - '**/*'
  base-directory: 'cdk.out'
