version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk@2.161.1
      - cd Backend
      - npm install

  pre_build:
    commands:
      - npm run build
      - cdk bootstrap --require-approval never

  build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then          
          # destroy CDK stack
          cdk destroy CatholicCharitiesStack --force \
            --context githubOwner="$GITHUB_OWNER" \
            --context githubRepo="$GITHUB_REPO" \
            --context githubToken="$GITHUB_TOKEN" \
            --context projectName="$PROJECT_NAME" \
            --context urlFilesPath="$URL_FILES_PATH" \
            --context identityCenterInstanceArn="$IDENTITY_CENTER_INSTANCE_ARN"
        else
          echo "=== PHASE 1: Backend Deployment ==="
          cdk deploy CatholicCharitiesStack --require-approval never \
            --context githubOwner="$GITHUB_OWNER" \
            --context githubRepo="$GITHUB_REPO" \
            --context githubToken="$GITHUB_TOKEN" \
            --context projectName="$PROJECT_NAME" \
            --context urlFilesPath="$URL_FILES_PATH" \
            --context identityCenterInstanceArn="$IDENTITY_CENTER_INSTANCE_ARN" \
            --outputs-file outputs.json
          
          API_URL=$(cat outputs.json | jq -r '.CatholicCharitiesStack.APIGatewayURL // empty')
          FRONTEND_BUILD_BUCKET=$(cat outputs.json | jq -r '.CatholicCharitiesStack.FrontendBuildBucketName // empty')
          
          if [ -z "$API_URL" ] || [ -z "$FRONTEND_BUILD_BUCKET" ]; then
            echo "Error: Could not extract required outputs from CDK deployment"
            exit 1
          fi
          
          echo "=== PHASE 2: Testing API Endpoints ==="
          HEALTH_RESPONSE=$(curl -s -w "%{http_code}" "${API_URL}health" || echo "000")
          if echo "$HEALTH_RESPONSE" | grep -q "200"; then
            echo "✅ API Gateway health check passed"
          else
            echo "⚠️ API Gateway health check failed"
          fi
          
          echo "=== PHASE 3: Triggering Data Source Sync ==="
          DATA_SOURCE_INFO=$(cat outputs.json | jq -r '.CatholicCharitiesStack.DataSourceInfo')
          APPLICATION_ID=$(cat outputs.json | jq -r '.CatholicCharitiesStack.QBusinessApplicationId')
          INDEX_ID=$(cat outputs.json | jq -r '.CatholicCharitiesStack.QBusinessIndexId')
          
          echo "$DATA_SOURCE_INFO" | jq -r '.[] | @base64' | while read -r data_source; do
            DS_ID=$(echo "$data_source" | base64 -d | jq -r '.id')
            DS_NAME=$(echo "$data_source" | base64 -d | jq -r '.name')
            aws qbusiness start-data-source-sync-job \
              --application-id "$APPLICATION_ID" \
              --data-source-id "$DS_ID" \
              --index-id "$INDEX_ID" \
              --region "$CDK_DEFAULT_REGION" || echo "Sync job may already be running for $DS_NAME"
          done
          
          echo "=== PHASE 4: Amplify App Setup ==="
          # Check if Amplify app already exists
          echo "Creating/updating Amplify app..."
          AMPLIFY_APP_ID=$(aws amplify create-app \
            --name "${PROJECT_NAME}-frontend" \
            --platform WEB \
            --environment-variables "REACT_APP_API_BASE_URL=$API_URL,REACT_APP_CHAT_ENDPOINT=${API_URL}chat,REACT_APP_HEALTH_ENDPOINT=${API_URL}health" \
            --query 'app.appId' \
            --output text 2>/dev/null || \
            aws amplify list-apps \
            --query "apps[?name=='${PROJECT_NAME}-frontend'].appId" \
            --output text)
            
          aws amplify create-branch \
            --app-id "$AMPLIFY_APP_ID" \
            --branch-name main \
            --stage PRODUCTION \
            --environment-variables "REACT_APP_API_BASE_URL=$API_URL,REACT_APP_CHAT_ENDPOINT=${API_URL}chat,REACT_APP_HEALTH_ENDPOINT=${API_URL}health" \
            --no-cli-pager 2>/dev/null || echo "Branch already exists"

          
          # Update the Lambda function with the Amplify App ID
          aws lambda update-function-configuration \
            --function-name "$(cat outputs.json | jq -r '.CatholicCharitiesStack.AmplifyDeployerFunctionName')" \
            --environment "Variables={AMPLIFY_APP_ID=$AMPLIFY_APP_ID}"
          
          echo "=== PHASE 5: Frontend Build and Automated Deployment ==="
          cd ../Frontend
          
          # Set build configuration
          export PUBLIC_URL=""
          export GENERATE_SOURCEMAP=false
          
          # Create environment file
          echo "REACT_APP_API_BASE_URL=$API_URL" > .env.production
          echo "REACT_APP_CHAT_ENDPOINT=${API_URL}chat" >> .env.production
          echo "REACT_APP_HEALTH_ENDPOINT=${API_URL}health" >> .env.production
          echo "PUBLIC_URL=" >> .env.production
          echo "GENERATE_SOURCEMAP=false" >> .env.production
          
          # Clean and build
          rm -rf build/ node_modules/.cache/
          npm ci --production=false
          npm run build
          
          # Verify build
          if [ ! -f "build/index.html" ]; then
            echo "❌ ERROR: Build failed - index.html not found!"
            exit 1
          fi
          
          if grep -q "%PUBLIC_URL%" build/index.html; then
            echo "❌ ERROR: Build incomplete - %PUBLIC_URL% not replaced!"
            exit 1
          fi
          
          echo "✅ Build successful"
          
          # Create and upload build artifact
          cd build
          zip -r ../build.zip . -x "*.DS_Store" "*.map"
          cd ..
          
          BUILD_KEY="builds/build-$(date +%s).zip"
          aws s3 cp build.zip s3://$FRONTEND_BUILD_BUCKET/$BUILD_KEY
          
          echo "✅ Build artifact uploaded to S3: $BUILD_KEY"
          echo "🚀 Automated deployment will start via EventBridge trigger"
          echo "📱 Amplify App URL: https://main.$AMPLIFY_APP_ID.amplifyapp.com"
          
          # Store Amplify App ID for post_build
          echo "$AMPLIFY_APP_ID" > ../amplify_app_id.txt
          
          cd ../Backend
        fi

  post_build:
    commands:
      - echo "=== Deployment Complete ==="
      - |
        if [ "$ACTION" = "deploy" ]; then
          AMPLIFY_APP_ID=$(cat ../amplify_app_id.txt 2>/dev/null || echo "")
          echo "🎉 Hybrid Deployment Summary:"
          echo "✅ Backend: Deployed via CloudFormation"
          echo "✅ Amplify App: Created/Updated via CLI"
          echo "✅ Frontend: Automated deployment triggered via S3 upload"
          echo ""
          echo "🔗 URLs:"
          echo "Chat API: ${API_URL}chat"
          echo "Health Check: ${API_URL}health"
          if [ -n "$AMPLIFY_APP_ID" ]; then
            echo "Amplify URL: https://main.$AMPLIFY_APP_ID.amplifyapp.com"
          fi
          echo ""
          echo "📊 Monitor:"
          echo "- Q Business data sync in Q Business Console"
          echo "- Amplify deployment in Amplify Console"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: 'cdk.out'
